package me.synology.murali.eaglebook;

public enum SlotAvailable {
	UNITIALIASED, DATE_AVAILABLE, DATE_UNAVAILABLE, SLOT_AVAILABLE, SLOT_UNAVAILABLE, SPECIFIC_AVAILABLE, SPECIFIC_UNAVAILABLE, COURT_AVAILABLE, COURT_UNAVAILABLE;
	
}
